export enum ErrorCode {
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
    TASK_ALREADY_SYNCED = 'TASK_ALREADY_SYNCED',
    TASK_NOT_FOUND = 'TASK_NOT_FOUND',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
