-- Baseline v2 (squashed): schema + enums
CREATE SCHEMA IF NOT EXISTS "public";

CREATE TYPE "Role" AS ENUM ('SCRUM_MASTER', 'DEVELOPER');
CREATE TYPE "AuthTokenType" AS ENUM ('EMAIL_VERIFICATION', 'PASSWORD_RESET');
CREATE TYPE "MeetingStatus" AS ENUM ('UPLOADED', 'PROCESSING', 'TASKS_EXTRACTED', 'FAILED');
CREATE TYPE "TaskStatus" AS ENUM ('EXTRACTED', 'SENT_TO_DEVELOPER', 'APPROVED', 'REJECTED', 'SYNCED');
CREATE TYPE "TaskSource" AS ENUM ('MANUAL', 'MEETING_EXTRACTION', 'JIRA_IMPORT');
CREATE TYPE "JiraProposalAction" AS ENUM ('CREATE', 'TRANSITION');
CREATE TYPE "ProjectMemberStatus" AS ENUM ('PENDING', 'ACTIVE');
CREATE TYPE "PullRequestState" AS ENUM ('OPEN', 'CLOSED');
CREATE TYPE "BlockerType" AS ENUM ('STALE_PR', 'NO_REVIEWERS', 'WAITING_REVIEW', 'DRAFT_TOO_LONG');
